version: "3.4"

services:
  server:
      image: chat-app-server
      build: ./server
      ports:
        - "5000:5000"
      volumes:
        - ./server/:/server 
        - /usr/src/app/node_modules
      depends_on:
        - mongo
      networks:
        - mern-app
      environment:  
        PORT: 5000
        MONGO_URL: "mongodb://mongo"      

  client:
    image: chat-app-client
    build: ./client 
    ports:
      - "3000:3000"
    volumes: 
      - ./client:/client
      - /usr/src/app/node_modules
    networks:
      - mern-app
   
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - ./data:/data/db
  
networks:
  mern-app:
    driver: bridge

